/**
 * Storyboards des 24 épisodes « Automatise ça » (une vidéo motion design par épisode).
 *
 * accroche   : les 3 premières secondes. *mots* = mis en valeur.
 * accrocheB  : saison 2 — une 2e version de la vidéo est rendue pour le test A/B (Instagram / TikTok).
 * cible      : l'étiquette « 🤯 ça change tout pour… », façon @drcintas.
 * comp       : ce qui s'anime dans le téléphone (chat, notif, sheet, cards, doc, stats, slots, qr).
 * etapes     : texte à l'écran, court (la version longue est dans le README de l'épisode).
 * cta        : keyword (Commentez MOT) | save (📌) | share (📤) | bio (🔗).
 */
export const episodes = [
  // ---------- Saison 1 · Octobre ----------
  {
    nom: "ep01-menu-whatsapp", num: 1, cible: "☕ Pour les cafés et restos",
    accroche: "Vos clients vous écrivent *« c'est combien ? »* 50 fois par jour ?",
    resultat: "Chaque produit ouvre WhatsApp avec la commande déjà écrite", gratuit: true,
    comp: { type: "chat", titre: "Café Lumière", messages: [
      { side: "sys", text: "Le client appuie sur « Commander »", t: 0.2 },
      { side: "out", text: "Bonjour Café Lumière ! Je voudrais commander :\n• 1 × Latte miel & cannelle (300 DA)\n\nMerci !", t: 0.9 },
      { side: "in", text: "C'est noté ✅ Prêt dans 10 minutes ☕", t: 3.2 },
    ] },
    etapes: ["Écrivez votre menu et vos prix", "Créez le lien wa.me/ + votre numéro", "Ajoutez le message déjà écrit", "Un bouton « Commander » par produit"],
    cta: { type: "keyword", mot: "MENU", suite: "et je vous envoie la démo" },
  },
  {
    nom: "ep02-commande-boutique", num: 2, cible: "🛍️ Pour les boutiques",
    accroche: "Fini les *10 messages* pour une seule commande.",
    resultat: "Taille, couleur, quantité et adresse arrivent en un seul message", gratuit: true,
    comp: { type: "chat", titre: "Boutique Atlas", messages: [
      { side: "out", text: "🛍️ Nouvelle commande\nRobe Kaftan Sahara\nTaille M · Terracotta · × 2\nTotal : 9 800 DA\n\nAmina B. · Hydra, Alger", t: 0.5 },
      { side: "in", text: "Merci Amina ! Livraison demain 🚚", t: 3.0 },
    ] },
    etapes: ["Ajoutez taille, couleur et quantité", "Ajoutez nom, téléphone et adresse", "Tout est assemblé en un seul message", "Le bouton l'envoie sur WhatsApp"],
    cta: { type: "save", texte: "Enregistrez cette vidéo pour votre boutique" },
  },
  {
    nom: "ep03-qr-code-whatsapp", num: 3, cible: "📱 Pour les cafés et boutiques",
    accroche: "Ce QR code m'a pris *2 minutes.*",
    resultat: "Le client scanne : WhatsApp s'ouvre avec son message déjà écrit", gratuit: true,
    comp: { type: "qr", titre: "Café Lumière", sous: "Commandez depuis votre table",
      lien: "https://wa.me/213000000000?text=Bonjour%20Caf%C3%A9%20Lumi%C3%A8re", message: "Bonjour Café Lumière ! Je suis à la table 4 et je voudrais commander :" },
    etapes: ["Créez le lien wa.me/ + votre numéro", "Ajoutez ?text= et le message", "Transformez le lien en QR code", "Imprimez-le : tables, vitrine, sacs"],
    cta: { type: "keyword", mot: "QR", suite: "pour avoir le vôtre" },
  },
  {
    nom: "ep04-reservation-sheets", num: 4, cible: "💇‍♀️ Pour les salons et instituts",
    accroche: "Votre agenda est encore dans vos *messages Instagram* ?",
    resultat: "Chaque réservation s'ajoute toute seule dans Google Sheets", gratuit: true,
    comp: { type: "sheet", titre: "Réservations — Salon Jasmin", colonnes: ["Nom", "Prestation", "Date", "Heure"], lignes: [
      { cells: ["Yasmine B.", "Couleur", "12/10", "10:00"] },
      { cells: ["Nadia K.", "Manucure", "12/10", "14:30"], t: 0.8 },
      { cells: ["Sara H.", "Coupe", "13/10", "09:30"], t: 2.0 },
      { cells: ["Lina M.", "Kératine", "13/10", "11:00"], t: 3.2 },
    ], toast: { texte: "✅ Nouvelle réservation enregistrée", t: 3.5 } },
    etapes: ["Un Google Sheets « Réservations »", "Collez le petit script Apps Script", "Déployez-le en « Application Web »", "Le formulaire remplit le tableau"],
    cta: { type: "keyword", mot: "AGENDA", suite: "pour recevoir le modèle" },
  },
  {
    nom: "ep05-rappel-veille", num: 5, cible: "💇‍♀️ Pour les salons et cliniques",
    accroche: "Les rendez-vous oubliés vous coûtent *combien* par mois ?",
    resultat: "La veille à 18h, le rappel part tout seul", gratuit: true,
    comp: { type: "notif", heure: "17:59", heureApres: "18:00", change: 0.8, date: "mercredi 14 octobre", notifs: [
      { icone: "💬", app: "WhatsApp · Salon Jasmin", titre: "Petit rappel 👋", texte: "Votre rendez-vous « Couleur » est demain à 10h30. Un empêchement ? Répondez pour décaler.", t: 1.1 },
    ] },
    etapes: ["Partez du tableau de réservations", "Ajoutez le script de rappel", "Écrivez votre message, avec le prénom", "Il tourne chaque jour à 18h"],
    cta: { type: "share", texte: "Partagez à un salon qui en a besoin" },
  },
  {
    nom: "ep06-creneaux-en-ligne", num: 6, cible: "🌙 Pour les salons",
    accroche: "Vos clients réservent *pendant que vous dormez.*",
    resultat: "Seuls les créneaux libres s'affichent, la confirmation part tout de suite", gratuit: true,
    comp: { type: "slots", heure: "23:04", titre: "Salon Jasmin", jours: ["mar. 13", "mer. 14", "jeu. 15", "ven. 16"], jourChoisi: 2,
      creneaux: ["09:30", "11:00", "14:00", "15:30", "16:00", "17:30"], choix: "15:30", tChoix: 1.6, tConfirm: 2.6,
      confirmation: "Jeudi 15 octobre à 15h30\nConfirmation envoyée à 23h04" },
    etapes: ["Fixez vos horaires et vos durées", "La page lit les créneaux déjà pris", "Le client choisit, le créneau disparaît", "La confirmation part, même à 23h"],
    cta: { type: "keyword", mot: "RDV", suite: "pour avoir la même chose" },
  },
  {
    nom: "ep07-devis-alerte", num: 7, cible: "🔨 Pour les artisans et services",
    accroche: "Un client demande un devis. Vous répondez 2 jours après. *Il est déjà parti.*",
    resultat: "La demande arrive sur votre téléphone à la seconde", gratuit: true,
    comp: { type: "notif", heure: "10:42", date: "lundi 19 octobre", notifs: [
      { icone: "✉️", app: "Gmail · Alerte devis", titre: "🔔 Nouveau devis : salle de bain", texte: "Karim Ouali · 12 m² · 150 000 – 500 000 DA · Dès que possible", t: 0.8 },
      { icone: "💬", app: "WhatsApp", titre: "Vous → Karim", texte: "Bonjour Karim, ici Rénov' Express. Vous êtes disponible pour un appel ?", t: 2.6 },
    ] },
    etapes: ["Un formulaire avec les bonnes questions", "Chaque demande va dans « Prospects »", "Une alerte arrive sur votre téléphone", "Vous rappelez en 5 minutes"],
    cta: { type: "keyword", mot: "DEVIS", suite: "pour la démo" },
  },
  {
    nom: "ep08-relance-auto", num: 8, cible: "🔨 Pour les artisans et services",
    accroche: "*La plupart des ventes* se font après la relance. Vous relancez ?",
    resultat: "2 jours sans réponse ? La relance part toute seule", gratuit: true,
    comp: { type: "chat", titre: "Samia L.", statut: "prospect · cuisine", messages: [
      { side: "sys", text: "Jour 2 · 10h00 · relance automatique", t: 0.3 },
      { side: "out", text: "Bonjour Samia, je reviens vers vous pour votre projet de cuisine. Je peux passer voir le chantier cette semaine ?", t: 0.9 },
      { side: "in", text: "Oui ! Jeudi après-midi, ça vous va ? 🙂", t: 3.3 },
    ] },
    etapes: ["Un statut par prospect", "Il répond ? Passez-le en « Répondu »", "Chaque matin, le script repère les silences", "Une seule relance polie, datée"],
    cta: { type: "save", texte: "Enregistrez pour ne plus jamais oublier une relance" },
  },
  {
    nom: "ep09-tableau-prospects", num: 9, cible: "📊 Pour tous les commerces",
    accroche: "Instagram, Google ou bouche-à-oreille : vous savez *ce qui marche* ?",
    resultat: "Chaque formulaire note sa source, le tableau compte tout seul", gratuit: true,
    comp: { type: "stats", titre: "D'où viennent vos clients ?", kpis: [
      { label: "Prospects · 30 jours", valeur: 41 }, { label: "Meilleur canal", texte: "Instagram" },
    ], barres: [
      { label: "Instagram", valeur: 15 }, { label: "Google", valeur: 9 }, { label: "Bouche-à-oreille", valeur: 8 }, { label: "TikTok", valeur: 5 }, { label: "Facebook", valeur: 4 },
    ] },
    etapes: ["Demandez « Comment nous avez-vous connus ? »", "Un lien par plateforme : ?source=…", "Chaque prospect arrive avec sa source", "Le tableau compte par canal"],
    cta: { type: "keyword", mot: "CLIENTS", suite: "pour recevoir le tableau" },
  },
  {
    nom: "ep10-chatbot-ia", num: 10, cible: "🤖 Pour tous les commerces",
    accroche: "Horaires, prix, adresse : vous répondez encore *à la main* ?",
    resultat: "Un assistant qui répond en 2 secondes, avec vos infos", gratuit: false,
    comp: { type: "chat", titre: "Assistant · Salon Jasmin", statut: "répond tout de suite", messages: [
      { side: "out", text: "Vous êtes ouverts le lundi ?", t: 0.3 },
      { side: "in", text: "Le salon est fermé le lundi. On vous accueille du mardi au samedi, de 9h à 19h 🌸", t: 1.5 },
      { side: "out", text: "Et une couleur, c'est combien ?", t: 2.6 },
      { side: "in", text: "Couleur : à partir de 5 000 DA, comptez 1h30.", t: 3.8 },
    ] },
    etapes: ["Écrivez vos infos une fois", "L'IA ne répond qu'avec ces infos", "Ajoutez la fenêtre de discussion", "Le reste arrive sur votre WhatsApp"],
    cta: { type: "keyword", mot: "IA", suite: "pour voir la démo" },
  },
  {
    nom: "ep11-reponses-avis-ia", num: 11, cible: "⭐ Pour les restos et commerces",
    accroche: "Un avis négatif sans réponse *fait fuir* les clients.",
    resultat: "L'IA prépare la réponse, vous validez", gratuit: false,
    comp: { type: "chat", titre: "Avis Google · Le Figuier", statut: "1 nouvel avis", messages: [
      { side: "in", direct: true, text: "★★☆☆☆ Leïla M.\nPlats bons, mais 45 minutes d'attente un vendredi soir…", t: 0.2 },
      { side: "out", text: "Bonjour Leïla, merci pour votre retour. Nous sommes sincèrement désolés pour cette attente : votre message a été partagé avec toute l'équipe.", t: 1.0, type: 2.2 },
      { side: "ok", text: "✓ Validée et publiée", t: 3.9 },
    ] },
    etapes: ["Chaque nouvel avis arrive dans une liste", "L'IA écrit un brouillon précis et poli", "Vous relisez : rien ne part sans vous", "Un clic : l'avis a sa réponse"],
    cta: { type: "save", texte: "Enregistrez cette astuce" },
  },
  {
    nom: "ep12-site-salon-complet", num: 12, cible: "🚀 Tout le mois dans un site",
    accroche: "Voici tout ce qu'on a construit ce mois-ci, *dans un seul site.*",
    resultat: "Réservation, rappel, Google Sheets, assistant IA et WhatsApp", gratuit: false,
    comp: { type: "cards", titre: "Salon Jasmin · tout en un", items: [
      { icone: "📅", titre: "Réservation 24h/24", sous: "seuls les créneaux libres", etiquette: "✓ Inclus", ton: "ok" },
      { icone: "📊", titre: "Google Sheets", sous: "se remplit tout seul", etiquette: "✓ Inclus", ton: "ok" },
      { icone: "⏰", titre: "Rappel la veille", sous: "à 18h, automatique", etiquette: "✓ Inclus", ton: "ok" },
      { icone: "🤖", titre: "Assistant IA", sous: "répond aux questions", etiquette: "✓ Inclus", ton: "ok" },
      { icone: "💬", titre: "Bouton WhatsApp", sous: "partout sur le site", etiquette: "✓ Inclus", ton: "ok" },
    ] },
    etapes: ["Une page claire : prestations, prix, avis", "Réservation sur les créneaux libres", "Confirmation, puis rappel la veille", "Assistant IA et WhatsApp pour le reste"],
    cta: { type: "bio", texte: "Vous voulez le même ? Lien en bio : ClickVente" },
  },

  // ---------- Saison 2 · Novembre (accroche A + accroche B) ----------
  {
    nom: "ep13-devis-ia-60-secondes", num: 13, cible: "📸 Pour les photographes et l'événementiel",
    accroche: "Ce devis s'est écrit tout seul en *60 secondes.*",
    accrocheB: "« Je vous envoie le devis ce soir. » Trois jours plus tard, *le couple avait signé ailleurs.*",
    resultat: "6 champs après l'appel : la proposition est prête", gratuit: false,
    comp: { type: "doc", marque: "Studio Nour", ref: "PR-2026-0118", titre: "Proposition pour Sarah & Yanis",
      lignes: [["Formule Signature · 8 h", "110 000 DA"], ["Album photo 30×30", "25 000 DA"]],
      total: { label: "Total", valeur: 135000 }, sous: { label: "Acompte 30 %", valeur: 40500 }, tampon: "Prête en 1 min ✓" },
    etapes: ["Après l'appel : 6 champs, 1 minute", "Les prix se calculent tout seuls", "L'IA écrit le texte, vous relisez", "PDF ou WhatsApp, tout de suite"],
    cta: { type: "keyword", mot: "PROPOSITION", suite: "et je vous envoie le modèle" },
  },
  {
    nom: "ep14-tri-prospects", num: 14, cible: "🔨 Pour les artisans et services",
    accroche: "*30 demandes* de devis cette semaine. Lesquelles rappeler en premier ?",
    accrocheB: "Arrêtez de répondre aux demandes *dans l'ordre d'arrivée.*",
    resultat: "Chaque demande a une note sur 100 et se range toute seule", gratuit: true,
    comp: { type: "cards", titre: "Demandes de devis", items: [
      { score: 88, ton: "hot", titre: "Lyes Brahimi", sous: "Cuisine · Dès que possible", etiquette: "🔥 Chaud" },
      { score: 85, ton: "hot", titre: "Famille Meziane", sous: "Rénovation · 95 m²", etiquette: "🔥 Chaud" },
      { score: 67, ton: "warm", titre: "Nadia T.", sous: "Peinture · Dans le mois", etiquette: "🌤️ Tiède" },
      { score: 16, ton: "cold", titre: "Hakim B.", sous: "Peinture · Je me renseigne", etiquette: "❄️ Froid" },
    ] },
    etapes: ["Listez ce qui fait un bon client", "Des points pour chaque réponse", "Chaque demande se range toute seule", "Rappelez les chauds d'abord"],
    cta: { type: "keyword", mot: "TRI", suite: "pour recevoir la grille de points" },
  },
  {
    nom: "ep15-photo-semaine-posts", num: 15, cible: "📸 Pour les cafés et boutiques",
    accroche: "Une photo de votre produit. *Sept jours de contenu.* Deux minutes.",
    accrocheB: "Vous ne manquez pas d'idées. *Vous manquez de temps* pour les écrire.",
    resultat: "Une photo + une phrase = une semaine de posts", gratuit: false,
    comp: { type: "cards", titre: "🍵 Nouveau latte pistache", items: [
      { icone: "📸", titre: "Post Instagram", sous: "légende + hashtags", etiquette: "Prêt ✓", ton: "ok" },
      { icone: "📱", titre: "3 stories", sous: "avec un sondage", etiquette: "Prêt ✓", ton: "ok" },
      { icone: "🟢", titre: "Statut WhatsApp", sous: "une ligne", etiquette: "Prêt ✓", ton: "ok" },
      { icone: "📍", titre: "Post Google", sous: "pour votre fiche", etiquette: "Prêt ✓", ton: "ok" },
      { icone: "🎬", titre: "Script de Reel", sous: "3 plans à filmer", etiquette: "Prêt ✓", ton: "ok" },
      { icone: "🗓️", titre: "Planning", sous: "du lundi au dimanche", etiquette: "Prêt ✓", ton: "ok" },
    ] },
    etapes: ["Une photo, à la lumière du jour", "Votre idée en une phrase", "L'IA écrit posts, stories et Reel", "Copiez, publiez, suivez le planning"],
    cta: { type: "keyword", mot: "POST", suite: "pour tester l'outil" },
  },
  {
    nom: "ep16-clients-perdus", num: 16, cible: "💇‍♀️ Pour les salons et instituts",
    accroche: "*23 clientes* ne sont pas revenues depuis 2 mois. Voici le message qui les fait revenir.",
    accrocheB: "Elle venait chaque mois. Puis plus rien. *Personne ne lui a écrit.*",
    resultat: "Chaque cliente perdue reçoit un message personnel", gratuit: true,
    comp: { type: "cards", titre: "23 clientes à faire revenir", items: [
      { icone: "S", titre: "Sara H.", sous: "Soin kératine · il y a 14 semaines", etiquette: "Envoyer", apres: { texte: "Envoyé ✓", t: 1.6 } },
      { icone: "Y", titre: "Yasmine B.", sous: "Couleur · il y a 11 semaines", etiquette: "Envoyer", apres: { texte: "Envoyé ✓", t: 2.2 } },
      { icone: "K", titre: "Kenza A.", sous: "Manucure · il y a 10 semaines", etiquette: "Envoyer", apres: { texte: "Envoyé ✓", t: 2.8 } },
      { icone: "L", titre: "Lina M.", sous: "Coupe · il y a 9 semaines", etiquette: "Envoyer", apres: { texte: "Envoyé ✓", t: 3.4 } },
    ], pied: { valeur: 24500, suffixe: " DA", texte: "si 6 clientes sur 23 reviennent", t: 3.9 } },
    etapes: ["Partez de votre fichier de rendez-vous", "Filtrez : pas venue depuis 60 jours", "Le message se personnalise tout seul", "Un geste par cliente pour l'envoyer"],
    cta: { type: "keyword", mot: "RETOUR", suite: "et je vous envoie le modèle" },
  },
  {
    nom: "ep17-demande-avis-auto", num: 17, cible: "⭐ Pour les salons, restos et cliniques",
    accroche: "Vos clientes adorent votre travail. *Pourquoi si peu d'avis Google* ?",
    accrocheB: "Ne demandez plus d'avis. *Programmez-les.*",
    resultat: "2 heures après le rendez-vous, le merci part avec le lien", gratuit: true,
    comp: { type: "notif", heure: "12:00", date: "mercredi 11 novembre", notifs: [
      { icone: "💬", app: "WhatsApp · Salon Jasmin", titre: "Merci Yasmine 🌸", texte: "Si vous avez 30 secondes, votre avis nous aide énormément : ⭐ laisser un avis sur Google", t: 0.8 },
      { icone: "⭐", app: "Google Business", titre: "Nouvel avis ★★★★★", texte: "« Couleur parfaite et accueil adorable ! »", t: 2.8 },
    ] },
    etapes: ["Récupérez le lien direct vers vos avis", "Un merci court, avec le prénom", "Il part 2 h après chaque rendez-vous", "Et un QR code au comptoir"],
    cta: { type: "keyword", mot: "AVIS", suite: "pour le message et le QR code" },
  },
  {
    nom: "ep18-facture-auto", num: 18, cible: "🧾 Pour les indépendants et services",
    accroche: "Une facture propre, numérotée et envoyée en *30 secondes.*",
    accrocheB: "Encore une soirée à faire *vos factures sur Word* ?",
    resultat: "Numéro, totaux, lien de paiement : tout se remplit seul", gratuit: true,
    comp: { type: "doc", marque: "Studio Nour", ref: "FA-2026-0043", titre: "Facture · Sarah & Yanis",
      lignes: [["Formule Signature", "110 000 DA"], ["Album photo 30×30", "25 000 DA"], ["Acompte reçu", "− 40 500 DA"]],
      total: { label: "Reste à payer", valeur: 94500 }, tampon: "Envoyée ✓" },
    etapes: ["Votre modèle et vos prix, une fois", "Choisissez le client et les prestations", "Le PDF part avec le lien de paiement", "Le tableau suit chaque facture"],
    cta: { type: "keyword", mot: "FACTURE", suite: "pour le modèle" },
  },
  {
    nom: "ep19-liste-attente-black-friday", num: 19, cible: "🖤 Spécial Black Friday",
    accroche: "Black Friday dans *11 jours.* Votre liste d'attente est prête ?",
    accrocheB: "Une promo postée le jour J, *c'est déjà trop tard.*",
    resultat: "Une page, un compte à rebours, une liste qui se remplit", gratuit: true,
    comp: { type: "stats", titre: "🖤 Black Friday · Boutique Atlas", kpis: [
      { label: "Jours restants", valeur: 11 }, { label: "Inscrites", valeur: 131 },
      { label: "Avec accord", texte: "100 %" }, { label: "Jour J", texte: "ven. 27" },
    ], note: { texte: "Le jour J : un geste par inscrite, message déjà écrit ✓", t: 2.6 } },
    etapes: ["Compte à rebours + formulaire", "Prénom, WhatsApp et accord", "Partagez le lien dès maintenant", "Le jour J, elles sont prévenues en premier"],
    cta: { type: "keyword", mot: "BLACK", suite: "et je vous envoie la page" },
  },
  {
    nom: "ep20-catalogue-google-sheets", num: 20, cible: "🛍️ Pour les boutiques",
    accroche: "Je change un chiffre dans Google Sheets… *et le site se met à jour.*",
    accrocheB: "« C'est encore disponible ? » *La question que vous lisez toute la journée.*",
    resultat: "Prix et stock viennent du tableau. Le stock revient ? On prévient.", gratuit: true,
    comp: { type: "sheet", titre: "Catalogue — Boutique Atlas", colonnes: ["Produit", "Prix", "Stock"], lignes: [
      { cells: ["Robe Kaftan", "4 900", "6"] }, { cells: ["Foulard soie", "1 800", "0"] },
      { cells: ["Sac cabas", "3 200", "2"] }, { cells: ["Sandales cuir", "3 900", "9"] },
    ], change: { ligne: 1, col: 2, vers: "5", t: 1.4 }, toast: { texte: "🔔 Foulard soie de retour : 2 clientes à prévenir", t: 2.4 } },
    etapes: ["Votre catalogue dans Google Sheets", "Publiez la feuille : le site la lit", "« Plus que 2 » et « Épuisé » s'affichent", "Le stock revient : vous savez qui prévenir"],
    cta: { type: "keyword", mot: "STOCK", suite: "pour le modèle" },
  },
  {
    nom: "ep21-prospects-entreprises", num: 21, cible: "🎁 Spécial commandes de fin d'année",
    accroche: "*50 entreprises* à contacter pour vos commandes de fin d'année. Trouvées en 5 minutes.",
    accrocheB: "Vous attendez les commandes de fin d'année ? *Les autres vont les chercher.*",
    resultat: "Une recherche : nom, téléphone, note Google et script d'appel", gratuit: false,
    comp: { type: "cards", titre: "Agences immobilières · Oran", items: [
      { icone: "🏢", titre: "Immo Oran Centre", sous: "★ 4,2 · Gambetta", etiquette: "📞 À appeler" },
      { icone: "🏢", titre: "Agence El Bahia", sous: "★ 4,6 · Akid Lotfi", etiquette: "📞 À appeler" },
      { icone: "🏢", titre: "Habitat Plus", sous: "★ 4,1 · Front de Mer", etiquette: "📞 À appeler" },
      { icone: "🏢", titre: "Agence Les Palmiers", sous: "★ 4,8 · Saint-Hubert", etiquette: "📞 À appeler", apres: { texte: "Intéressée ✓", t: 3.2 } },
    ], pied: { valeur: 50, texte: "entreprises avec téléphone", t: 2.4 } },
    etapes: ["Choisissez vos cibles", "Une recherche Google Maps par ville", "Un script d'appel par entreprise", "Vous appelez, la liste vous suit"],
    cta: { type: "keyword", mot: "PROSPECT", suite: "pour le script" },
  },
  {
    nom: "ep22-agent-commandes-ia", num: 22, cible: "🤖 Pour les cafés et restos",
    accroche: "« 2 cappu et un croissant pour 8h30. » *L'IA a fait le reste.*",
    accrocheB: "Un chatbot répond. *Un agent agit.* Voici la différence.",
    resultat: "L'agent comprend, demande ce qui manque, envoie la commande", gratuit: false,
    comp: { type: "chat", titre: "Café Lumière", statut: "commandes à emporter", messages: [
      { side: "out", text: "2 cappu et un croissant pour 8h30", t: 0.3 },
      { side: "in", text: "C'est noté ! C'est à quel prénom ?", t: 1.4 },
      { side: "out", text: "Sami", t: 2.3 },
      { side: "in", text: "Parfait Sami ! 2 × Cappuccino et 1 × Croissant, prêts pour 8h30 ✅", t: 3.4 },
      { side: "ok", text: "🧾 Envoyée au café · 620 DA", t: 4.4 },
    ] },
    etapes: ["Donnez votre carte à l'agent", "Le client écrit comme il parle", "Il manque quelque chose ? Une question", "La commande arrive sur votre WhatsApp"],
    cta: { type: "keyword", mot: "AGENT", suite: "pour la démo" },
  },
  {
    nom: "ep23-rapport-du-lundi", num: 23, cible: "📊 Pour les salons et commerces",
    accroche: "Chaque lundi à 8h, *ce message arrive tout seul.*",
    accrocheB: "Vous ne pouvez pas améliorer *ce que vous ne mesurez pas.*",
    resultat: "Votre semaine en un message, comparée à la précédente", gratuit: true,
    comp: { type: "stats", titre: "📊 Votre semaine", kpis: [
      { label: "Rendez-vous", valeur: 46, delta: "▲ 7 %" }, { label: "Chiffre (DA)", valeur: 200100, delta: "▲ 12 %" },
      { label: "Absences", valeur: 4, delta: "à surveiller", mauvais: true }, { label: "Nouvelles clientes", valeur: 14, delta: "▲ 8 de plus" },
    ], note: { texte: "Une action : activez le rappel la veille (épisode 5)", t: 2.8 } },
    etapes: ["Vos rendez-vous sont déjà dans Sheets", "Le script compte toute la semaine", "Il compare et propose une action", "Lundi 8h : le résumé arrive"],
    cta: { type: "keyword", mot: "LUNDI", suite: "pour le modèle" },
  },
  {
    nom: "ep24-diagnostic-5-automatisations", num: 24, cible: "🧠 Pour tous les commerces",
    accroche: "Si j'ouvrais un commerce demain, voici *les 5 automatisations* que je mettrais en place.",
    accrocheB: "24 épisodes en 2 mois. Si vous ne gardez que 5 automatisations, *gardez celles-là.*",
    resultat: "6 questions : vos 5 automatisations et le temps gagné", gratuit: true,
    comp: { type: "cards", titre: "Vos 5 automatisations", items: [
      { icone: "1", titre: "Le bouton WhatsApp", sous: "épisode 1" },
      { icone: "2", titre: "Créneaux + rappel la veille", sous: "épisodes 5 et 6" },
      { icone: "3", titre: "La demande d'avis", sous: "épisode 17" },
      { icone: "4", titre: "Les clients perdus", sous: "épisode 16" },
      { icone: "5", titre: "Le rapport du lundi", sous: "épisode 23" },
    ], pied: { texte: "Faites votre diagnostic : lien en bio", t: 3.2 } },
    titreEtapes: "Les 5 à garder 👇",
    etapes: ["Le bouton WhatsApp", "Créneaux en ligne + rappel la veille", "La demande d'avis après chaque visite", "Le message aux clients perdus", "Le rapport du lundi matin"],
    cta: { type: "bio", texte: "Faites votre diagnostic gratuit : lien en bio", suite: "ClickVente" },
  },
];
